# Basic
title: yiming_blog
subtitle: ä¸ªäººåšå®¢
description: æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººåšå®¢~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: æ›¾ç§‘
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: ä¸ªäººå­¦ä¹ 
url: "yimingzeng.github.io"

# Comment
comment:
    disqus: leopard
    # gitment: xxx // éœ€è¦ä¿®æ”¹ comments.htmlä¸­çš„client_idå’Œclient_secret
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    weibo:  
    github: yimingzeng
    # zhihu: panpanleopard
    # juejin: xxx
    jianshu: 2ada30d8d0f7
    # twitter: 
    mail: 1012785014@qq.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: xxxx  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: xxxx  
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/yimingzeng/yimingzeng.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  # enable: false
  scriptFrom: local # é»˜è®¤
  pluginRootPath: live2dw/ # æ’ä»¶åœ¨ç«™ç‚¹ä¸Šçš„æ ¹ç›®å½•(ç›¸å¯¹è·¯å¾„)
  pluginJsPath: lib/ # è„šæœ¬æ–‡ä»¶ç›¸å¯¹ä¸æ’ä»¶æ ¹ç›®å½•è·¯å¾„
  pluginModelPath: assets/ # æ¨¡å‹æ–‡ä»¶ç›¸å¯¹ä¸æ’ä»¶æ ¹ç›®å½•è·¯å¾„
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # ä½ çš„è‡ªå®šä¹‰ url
  tagMode: false # æ ‡ç­¾æ¨¡å¼, æ˜¯å¦ä»…æ›¿æ¢ live2d tagæ ‡ç­¾è€Œéæ’å…¥åˆ°æ‰€æœ‰é¡µé¢ä¸­
  debug: false # è°ƒè¯•, æ˜¯å¦åœ¨æ§åˆ¶å°è¾“å‡ºæ—¥å¿—
  model:
    use: lived_models\live2d-widget-model-koharu # npm-module package name
    # use: wanko # åšå®¢æ ¹ç›®å½•/live2d_models/ ä¸‹çš„ç›®å½•å
    # use: ./wives/wanko # ç›¸å¯¹äºåšå®¢æ ¹ç›®å½•çš„è·¯å¾„
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # ä½ çš„è‡ªå®šä¹‰ url
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true # æ‰‹æœºä¸­æ˜¯å¦å±•ç¤º


